# Generated by Django 2.2.24 on 2021-10-12 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_date', 'title'], 'verbose_name': 'Девушки', 'verbose_name_plural': 'Девушки'},
        ),
    ]
